### ISSUE TITLE
Not really a bug

### ISSUE THREAD

**Issue by Waffle2** [ivanizag/z80-mbc2-emu#1]
I was quite happy to see this project, as it helped me to confirm a problem on the MBC2 distribution.  The version of mbasic.com distributed has long been suspect - and when I ran it on your emulator, it trapped out immediately with "not implemented" instructions.  This is due to what appears to be a modified mbasic.com, vs the version on http://www.retroarchive.org/cpm/lang/lang.htm (version 5.21, that is). 

Thank you for making a faithful reproduction, and it came up easily.  Much appreciated!

**Comment by ivanizag** [comment]
Thank you for you kind words, I am happy this program was useful to you.

Yes, it looks like something is not right on the bundled mbasic.com. It has direct access to I/O port 0xF2. To be CP/M portable it should never do that. It may be a customised MBASIC for a specific real machine.

The last instructions it executes are:

```
==> 5f37:  DI                  PC:5f38 AF:0044 BC:0011 DE:6093 HL:0080 SP:60ed IX:0000 IY:0000 Flags:01000100 [f3 21 0d]
==> 5f38:  LD HL, 000dh        PC:5f3b AF:0044 BC:0011 DE:6093 HL:000d SP:60ed IX:0000 IY:0000 Flags:01000100 [21 0d 00]
==> 5f3b:  LD A, (HL)          PC:5f3c AF:0044 BC:0011 DE:6093 HL:000d SP:60ed IX:0000 IY:0000 Flags:01000100 [7e 21 00]
==> 5f3c:  LD HL, 0000h        PC:5f3f AF:0044 BC:0011 DE:6093 HL:0000 SP:60ed IX:0000 IY:0000 Flags:01000100 [21 00 00]
==> 5f3f:  LD (5f56h), A       PC:5f42 AF:0044 BC:0011 DE:6093 HL:0000 SP:60ed IX:0000 IY:0000 Flags:01000100 [32 56 5f]
==> 5f42:  AND A, dfh          PC:5f44 AF:0054 BC:0011 DE:6093 HL:0000 SP:60ed IX:0000 IY:0000 Flags:01010100 [e6 df d3]
==> 5f44:  OUT (f2h), A       <<NOP not implemented>>
```

**Comment by Waffle2** [comment]
That's exactly what I found, as well.  Thank you again for confirming it!
